# Generated by Django 5.1.6 on 2025-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="batch_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="serial_number",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
