# Generated by Django 5.2 on 2025-04-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_product_is_active_product_low_stock_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="low_stock_threshold",
        ),
        migrations.DeleteModel(
            name="InventoryNotification",
        ),
    ]
